site_name: AudioMuse-AI Documentation
docs_dir: web
site_url: https://gaurav7902.github.io/AudioMuse-AI/
repo_url: https://github.com/gaurav7902/AudioMuse-AI
repo_name: GitHub
edit_uri: edit/main/web/

nav:
  - Home: index.md
  - Algorithm: ALGORITHM.md
  - Architecture: ARCHITECTURE.md
  - Deployment: DEPLOYMENT.md
  - FAQ: FAQ.md
  - GPU: GPU.md
  - Parameters: PARAMETERS.md
  - Authentication: AUTH.md

theme: readthedocs
